### PR TITLE
feat/DeleteEverything

### PR DESCRIPTION
**Pull request by gg119**
This is a dangerous doomsday pull request. If approved by two people the entire source folder will be gone 😈😈😈😈😈😈😈. But little do y'all know, the administrator can merge the pull request!

### CODE REVIEW

**Review by Lhito — CHANGES_REQUESTED** [review]
center the titles boi

**Review by byluz — CHANGES_REQUESTED** [review]
nice try

**Review by gg119 — COMMENTED** [review]
Fixed !!

**Review by GlacierNester — CHANGES_REQUESTED** [review]
Needs more deletion

**Pull request closed without merging**
